### ISSUE TITLE
Looking forward to the pretrained model and demo script

### ISSUE THREAD

**Issue by goldentimecoolk** [KyanChen/OvarNet#4]
What an amazing work! It would benefit a lot to the community if more supports are open source.

**Comment by Qinying-Liu** [comment]
+1

**Comment by njustczr** [comment]
+1 readme能写详细点吗

**Comment by park-youngjae** [comment]
+1

**Comment by CaffeineLiqueur** [comment]
+1

**Comment by RihoZhu** [comment]
+1

**Comment by Code-kunkun** [comment]
+1

**Comment by KyanChen** [comment]
The code is being reorganized and the ckpt will be open-source, about a week, please wait a moment.
