### ISSUE TITLE
bug in clipattr_img_crop_dataset.py

### ISSUE THREAD

**Issue by Code-kunkun** [KyanChen/OvarNet#5]
<img width="1078" alt="image" src="https://github.com/KyanChen/OvarNet/assets/58265850/a2a39247-cb45-4e4a-8b4a-b2c23e76f1fe">
i wonder where the `self.read_data` is and the `pattern` is not defined before.

[code](https://github.com/KyanChen/OvarNet/blob/0a2ccd8d50ea04393de9d5a1ce4f79a399bd1d5f/mmdet/datasets_my/clipattr_img_crop_dataset.py#L106)

**Comment by syo093c** [comment]
Yeah, the author said that he will update and refactor the code this week, but he seems very busy. However, I really hope that this excellent work can be further researched by more people.

**Comment by KyanChen** [comment]
open_category is always False

**Comment by Originlightwkp** [comment]
> <img alt="image" width="1078" src="https://user-images.githubusercontent.com/58265850/258002307-a2a39247-cb45-4e4a-8b4a-b2c23e76f1fe.png"> i wonder where the `self.read_data` is and the `pattern` is not defined before.
> 
> [code](https://github.com/KyanChen/OvarNet/blob/0a2ccd8d50ea04393de9d5a1ce4f79a399bd1d5f/mmdet/datasets_my/clipattr_img_crop_dataset.py#L106)

i want to ask how to reproduce the project, which .py should run?
